"""initial tables

Revision ID: 08aa804e0684
Revises: e98a83f35a62
Create Date: 2025-11-25 13:02:39.960909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08aa804e0684'
down_revision: Union[str, Sequence[str], None] = 'e98a83f35a62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=False))
    op.drop_constraint(op.f('users_whatsapp_number_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['phone_number'])
    op.drop_column('users', 'whatsapp_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('whatsapp_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_whatsapp_number_key'), 'users', ['whatsapp_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
