"""add shop_name to users

Revision ID: 84339c744977
Revises: 7cbeca433045
Create Date: 2025-11-25 13:33:17.697892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84339c744977'
down_revision: Union[str, Sequence[str], None] = '7cbeca433045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('shop_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'shop_name')
    # ### end Alembic commands ###
